# Generated by Django 4.2 on 2023-05-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_postbase_description_alter_postbase_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('postbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.postbase')),
                ('topic', models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('BlockChain ', 'BlockChain'), ('3D Art', '3D Art')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects/')),
                ('maincontent', models.TextField(blank=True, default='default', null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectpost')),
            ],
            bases=('core.postbase',),
        ),
    ]
