# Generated by Django 4.1.5 on 2023-02-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_postbase_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('postbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.postbase')),
                ('field', models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('BlockChain ', 'BlockChain'), ('3D Art', '3D Art')], max_length=20)),
                ('just_test', models.CharField(max_length=100, null=True)),
            ],
            bases=('core.postbase',),
        ),
    ]
