# Generated by Django 4.1.5 on 2023-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='just_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
