# Generated by Django 4.1.5 on 2023-02-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectpost_just_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpost',
            old_name='field',
            new_name='fields',
        ),
    ]
