# Generated by Django 4.2 on 2023-05-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectpost_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='model',
        ),
    ]
