# Generated by Django 4.2 on 2023-05-23 15:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectpost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='test',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
