# Generated by Django 4.2 on 2023-05-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectpost_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='test',
        ),
    ]
