# Generated by Django 4.1.5 on 2023-02-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectpostsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpostsection',
            name='section_num',
            field=models.IntegerField(null=True),
        ),
    ]
