# Generated by Django 4.1.5 on 2023-02-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_postbase_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('postbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.postbase')),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            bases=('core.postbase',),
        ),
    ]
