# Generated by Django 4.1.5 on 2023-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('B', 'Blog'), ('P', 'Photo'), ('T', 'Travel'), ('R', 'Review'), ('Pr', 'Project')], max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
