# Generated by Django 4.1.5 on 2023-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postbase_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbase',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Photo', 'Photo'), ('Travel', 'Travel'), ('Review', 'Review'), ('Project', 'Project')], max_length=7),
        ),
    ]
