# Generated by Django 4.1.5 on 2023-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_postbase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbase',
            name='post_time',
            field=models.DateField(),
        ),
    ]
