# Generated by Django 4.1.5 on 2023-04-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_postbase_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbase',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postbase',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
