# Generated by Django 4.1.5 on 2023-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='just_test',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
