# Generated by Django 4.1.5 on 2023-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='lens',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
